### ISSUE TITLE
more checks to PR

### ISSUE THREAD

**Issue by VegarRingdalAibel** [Aibel365/python-app-template#9]
Had a new user test on this.

Need to make it more "man" proof   (for users not reading documentation)

We need to add a check on PR request to see if `secrets.SOURCE_KEY` is filled out/added/not emoty.

And we should add how to create deploy key... save user from searching 😂 
`ssh-keygen -t ed25519 -C "email@whater.com"`

**Comment by VegarRingdalAibel** [comment]
Easiest fix to this would pro just to add this as a step
```
      - name: Check if secret SOURCE_KEY is added
        shell: python
        run: |
          if "${{ secrets.SOURCE_KEY }}" == "":
            raise Exception("Missing secret")

```

**Comment by VegarRingdalAibel** [comment]
@Krande 
Any suggestions?

**Comment by Krande** [comment]
Hey,

Sure, I think this is a really great! Here are some suggestions for improvement.

1) A github-actions bot that adds a "PR linting" comments 

The bot lists all the remaining tasks for you to fulfill the requirements of the PR. Conda forge uses this extensively and I find it to be really helpful (instead of having to go into each failing github actions test).  

I have started testing this [here](https://github.com/Krande/app-test/pull/4) and I can make a PR here once I have made it stable.
![image](https://github.com/Aibel365/python-app-template/assets/9642232/ea38c180-e242-4fe8-81e8-0ad1a7bcc289)

It's actually really easy to add a bot that comments. You just need to add  
```yaml
permissions:
  pull-requests: write
  
jobs:
  lintCheck:
    name: Python Check Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Add Label to PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Triage']
            })

      - name: Comment on PR
        if: >-
          !contains(github.event.pull_request.title, 'fix: ') &&
          !contains(github.event.pull_request.title, 'fix!: ') &&
          !contains(github.event.pull_request.title, 'feat: ') &&
          !contains(github.event.pull_request.title, 'feat!: ') &&
          !contains(github.event.pull_request.title, 'chore: ')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting! You need to start PR title with fix: feat: fix!: feat!: chore:'
            })
```

2) I would suggest splitting the "check_request.yaml" into a [callable workflow ](https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow) that does all the checking and when used it returns an object with all the boolean results for each test. The calling workflow contains then only the steps for reporting back to the user. That way it's easier to write a summary of which tests are failing and which are not. 

```yaml
on:
  workflow_call:
    inputs: #  (if there are any inputs you want to pass from the top level)
    outputs:
        pr_title_passing:
            description: Returns "true" if the title contains feat:, chore: etc..
            value: ${{ jobs.build.outputs.check_pr_title }} # refers to the job and step ID that checks and outputs the results

```


3) A conda and pip packaging checker. I have these already in some of my OS projects. I'll try to merge the work I've done there with this so that the "PR linting bot" also checks if your PR is ready for upload to conda/pip (I'll add separate tools in the semantic-release toml file for conda and pip respectively).
